# Generated by Django 3.2.4 on 2021-07-05 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0004_auto_20210705_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='productos',
            field=models.ManyToManyField(related_name='carritos', to='sitio.Producto'),
        ),
    ]
