# Generated by Django 3.2.4 on 2021-07-06 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitio', '0011_alter_carrito_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito',
            old_name='precio_total',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='carrito',
            name='productos',
        ),
        migrations.AlterField(
            model_name='carrito',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Carrito_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sitio.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitio.producto')),
            ],
        ),
    ]
